### PR TITLE
fix: set entry file in TypeScript configuration

### LINKED ISSUE #200: How best to handle Angular Directive, Pipe, Component with .ios or .android suffix?
I encountered this today and was not sure the best way forward. Curious if the core team has encountered this and how best things like this should be handled with AoT and Angular:
screen shot 2017-06-27 at 1 35 12 pm
screen shot 2017-06-27 at 1 35 24 pm

Here the `.d.ts` is merely used to satisfy the TypeScript compiler for the imports. In development, {N} builds the `.ios` and `.android` files into `.js` for the platform and causes no issue. However when run through this webpack plugin with AoT, this error is seen:

> ERROR in Cannot determine the module for class SlimSliderDirective in /MyApp/app/modules/player/directives/slider.directive.android.ts! Add SlimSliderDirective to the NgModule to fix it.
Cannot determine the module for class SlimSliderDirective in /MyApp/app/modules/player/directives/slider.directive.ios.ts! Add SlimSliderDirective to the NgModule to fix it.

Stumped. Any ideas? 

/cc @vakrilov @sis0k0 @hdeshev @vchimev @ivanbuhov @PeterStaev

### PR DESCRIPTION
**Pull request by sis0k0**
fixes #200

### CODE REVIEW

**Comment by vchimev** [comment]
js ng groceries

**Comment by vchimev** [comment]
groceries

**Comment by vchimev** [comment]
ng

**Comment by vchimev** [comment]
js

**Comment by sis0k0** [comment]
run ci

**Comment by sis0k0** [comment]
run ci

**Comment by vchimev** [comment]
run ci

**Pull request closed without merging**
