### PR TITLE
feat: support for Angular 5.1

### PR DESCRIPTION
**Pull request by sis0k0**
bumps versions of ngtools/webpack and related webpack dependencies
merge after https://github.com/NativeScript/nativescript-angular/pull/1134

### CODE REVIEW

**Comment by sis0k0** [comment]
run ci

**Comment by sis0k0** [comment]
webpack-groceries

**Comment by sis0k0** [comment]
groceries

**Comment by vchimev** [comment]
webpack

**Comment by vchimev** [comment]
webpack

**Comment by sis0k0** [comment]
webpack-groceries

**Comment by sis0k0** [comment]
webpack-groceries

**Pull request merged**
