### PR TITLE
feat(webpack-config): implement pass webpack config path

### PR DESCRIPTION
**Pull request by soarer1004**
## PR Checklist

- [ ] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA].
- [x] All existing tests are passing: https://github.com/NativeScript/nativescript-dev-webpack/blob/master/CONTRIBUTING.md#testing-locally-by-running-e2e-tests
- [ ] Tests for the changes are included.

## What is the current behavior?
Currently `webpack.config.js` is hardcoded in `projectFilesManager.js:60`. There is no way to specify webpack config path/name.

## What is the new behavior?
Now there is way to specify webpack config path/name in `nsconfig.json`, for example:
```json
{
    "webpackConfig": "webpack/config.js"
}
```

Implements #654.

[CLA]: http://www.nativescript.org/cla

### CODE REVIEW

**Comment by KristianDD** [comment]
Hi @soarer1004 ,
Thank you for the great contribution and excuse us for the late response. We have concentrated our efforts on preparing the NativeScript 6.0 release and are a bit behind on contribution PR reviews.

In 6.0 (and probably shortly after that) there will be major change in the `nativescript-dev-webpack` code base, that will affect the feature that you have suggested. We will consider integrating this solution or a similar one that solves the same problems/use cases in some of the post 6.0 releases. In order to have better understanding of the feature, could you please elaborate a bit more on how you are planning to use it and what problems it solves in your development process.

**Comment by edusperoni** [comment]
@KristianDD  I was just about to submit a similar PR, albeit simpler (just exposing env.webpackConfig https://github.com/edusperoni/nativescript-dev-webpack/tree/custom-config), so I'll chime in.

Usually when developing with webpack we have the choice to extend the default config or create multiple environments, like `webpack.config.shared.js`, `webpack.config.dev.js` and `webpack.config.prod.js`. This is a greater issue in {N} because the config is overwritten at every `nativescript-dev-webpack` update, so we have to reapply every change again.

Since everything is in `webpack.config.js`, running  a `diff` to find what we should reapply is a bit harder since our custom code is mixed in it. By allowing custom config files, we can do this:

```
// webpack.config.prod.js
const originalConfig = require("./webpack.config");

module.exports = env => {
    env.uglify = true;
    const config = originalConfig(env);
    config.plugins.push(new MyPlugin());
    return config;
};
```

So it would be useful to be able to specify the config at build time. I'm also against allowing to change it **only** in `nsconfig.json` for the reasons I already stated.

**Comment by rosen-vladimirov** [comment]
Thanks @soarer1004 , your input is really valuable for us. We'll keep this PR open and we'll take all your input when designing the way we'll improve the flexibility of using different and custom webpack.config.js files.

**Comment by manzapanza** [comment]
Same problem here. I would like to specify the name of the webpack file only for improve the organization of the config. files of the project and to maintain the same naming convention `*.tns.js` for NativeScript specific files. I have a shared project with Angular and Nativescript.. and by default Angular has a webpack builtin config (without a specific file in the project) and for NativeScript is named `webpack.config.js`. But now I need add a partial webpack file for Angular to setup `videojs-record` [as described here](https://github.com/collab-project/videojs-record/wiki/Angular) using `ngx-build-plus` and I would like use `webpack.config.js` for Angular and `webpack.config.tns.js` for NativeScript.

**Comment by halfnelson** [comment]
I would love something like this for Svelte Native. Currently every nativescript update clobbers the webpack changes and I need to re-add the svelte-loader. It also prevents me from having svelte native usable as a `--template` parameter to `tns create`.  If not this solution, one that lets you add plugins to a different config file, (like nsconfig.js) would suffice

**Comment by rosen-vladimirov** [comment]
Hey @soarer1004 ,
Thank you for this PR. We've applied a lot of changes since then, so this PR is no longer applicable for this repository. Currently NativeScript CLI is the one, which starts the webpack process, so based on your idea, I've managed to create a PR there: https://github.com/NativeScript/nativescript-cli/pull/5216

I'm closing this PR, but thanks for your time and effort!

**Pull request closed without merging**
