### PR TITLE
fix-next: cache package.json, starter.js and tns-java-classes.js between compilations

### PR DESCRIPTION
**Pull request by sis0k0**
The starter assets shouldn't be emitted on each compilation cycle, when using webpack with watch. Instead they should be cached if possible.

### CODE REVIEW

**Comment by sis0k0** [comment]
test

**Comment by sis0k0** [comment]
test

**Comment by sis0k0** [comment]
test

**Comment by sis0k0** [comment]
test

**Comment by sis0k0** [comment]
test

**Comment by SvetoslavTsenov** [comment]
test

**Comment by sis0k0** [comment]
test

**Comment by sis0k0** [comment]
test

**Pull request merged**
