### PR TITLE
fix: sourceMap not generated with Uglify

### LINKED ISSUE #816: Source maps not generated with --env.uglify
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 4.2.0
 - Cross-platform modules: 4.2.1
 - Android Runtime: 4.2.0
 - iOS Runtime: 4.2.0

**Describe the bug**
The default webpack configuration does not generate sourceMaps with --env.uglify (see https://github.com/webpack/webpack/issues/2704)

**To Reproduce**
`tns prepare android --bundle --env.uglify --env.sourceMap`

See that source maps are not generated.

**Expected behavior**

Source maps are generated.

**Additional context**
This is a simple fix in `webpack.config.js` by adding `sourceMap: !!sourceMap` to UglifyJsPlugin.

### PR DESCRIPTION
**Pull request by edusperoni**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA].
- [ ] All existing tests are passing: https://github.com/NativeScript/nativescript-dev-webpack/blob/master/CONTRIBUTING.md#testing-locally-by-running-e2e-tests
- [ ] Tests for the changes are included.

## What is the current behavior?
Source maps are not generated when `--env.uglify` is present

## What is the new behavior?
Source maps are generated normally with `--env.uglify`

Fixes #816.

I haven't run e2e tests, but this is pretty minor. I've tested this inside my app.

### CODE REVIEW

**Comment by etabakov** [comment]
@cla-bot check

**Comment by edusperoni** [comment]
I've updated the PR to support Vue.

**Comment by DimitarTachev** [comment]
run ci

**Comment by dtopuzov** [comment]
test

**Pull request merged**
