### PR TITLE
feat: allow extending webpack.config.js through env

### PR DESCRIPTION
**Pull request by rosen-vladimirov**
In case you need to extend the webpack.config.js, currently you cannot extend everything and you need to write a lot of custom logic. This PR adds the possibility to extend the appComponents, entries and alias through `env`.
Also update demo applications to use latest CLI feature for extending webpack.config.js
Merge after: https://github.com/NativeScript/nativescript-cli/pull/5216

## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA].
- [x] All existing tests are passing: https://github.com/NativeScript/nativescript-dev-webpack/blob/master/CONTRIBUTING.md#testing-locally-by-running-e2e-tests
- [ ] Tests for the changes are included.

## What is the new behavior?

Fixes/Implements/Closes #[Issue Number].

[CLA]: http://www.nativescript.org/cla

### CODE REVIEW

**Comment by rosen-vladimirov** [comment]
test ngapps

**Comment by rosen-vladimirov** [comment]
test webpack-apps

**Comment by rosen-vladimirov** [comment]
test webpack-apps

**Comment by dtopuzov** [comment]
test webpack-apps branch-webpack-apps#vladimirov/custom-configs

**Comment by dtopuzov** [comment]
test webpack-apps branch#webpack_apps vladimirov/custom-configs

**Comment by dtopuzov** [comment]
test webpack-apps branch#vladimirov/custom-configs

**Comment by jibon57** [comment]
@rosen-vladimirov thanks for excellent feature. How I'll add custom file type in `CopyWebpackPlugin`?

**Comment by rosen-vladimirov** [comment]
Hey @jibon57 , 
I've created a sample application demonstrating how you can achieve this: https://github.com/rosen-vladimirov/appCustomWebpackConfig
Check the README for more details.

**Pull request merged**
