### PR TITLE
fix: respect ts files on `test` command

### PR DESCRIPTION
**Pull request by Fatme**
Rel to:
https://github.com/NativeScript/nativescript-cli/issues/4477
https://github.com/NativeScript/nativescript-cli/issues/1798

## PR Checklist

- [ ] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ ] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [ ] You have signed the [CLA].
- [ ] All existing tests are passing: https://github.com/NativeScript/nativescript-dev-webpack/blob/master/CONTRIBUTING.md#testing-locally-by-running-e2e-tests
- [ ] Tests for the changes are included.

## What is the new behavior?

Fixes/Implements/Closes #[Issue Number].

[CLA]: http://www.nativescript.org/cla

### CODE REVIEW

**Comment by Fatme** [comment]
test package_version#latest

**Comment by Fatme** [comment]
test package_version#latest

**Comment by SvetoslavTsenov** [comment]
test package_version#master

**Comment by SvetoslavTsenov** [comment]
test package_version#rc

**Comment by SvetoslavTsenov** [comment]
test package_version#latest

**Comment by SvetoslavTsenov** [comment]
test package_version#rc

**Comment by SvetoslavTsenov** [comment]
test package_version#latest

**Comment by dtopuzov** [comment]
test package_version#latest branch#release

**Pull request merged**
