### PR TITLE
feat: make webpack deps production deps of the plugin

### PR DESCRIPTION
**Pull request by sis0k0**
implements #569 

BREAKING CHANGES:

The dependencies that were previously added by the nativescript-dev-webpack plugin to the project's package.json are now dependencies of the plugin itself.

MIGRATION:
1. Remove all obsolete dependencies from your project. You can do that by invoking the script:
```
./node_modules/.bin/update-ns-webpack --deps
```
2. [Angular] Add the following packages as devDependencies:
```
//package.json

"devDependencies": {
    "@angular-devkit/build-angular": "~0.7.0-rc.0",
    "@angular/compiler-cli": "~6.1.0-beta.1",
    //...
}
```

### CODE REVIEW

**Comment by sis0k0** [comment]
test

**Comment by sis0k0** [comment]
test

**Comment by vchimev** [comment]
After migration I get:
```
Error: Couldn't load webpack config from /Users/vchimev/Work/git/appNg/webpack.config.js. Original error:
Error: Cannot find module '@ngtools/webpack'
    at getWebpackConfig (/Users/vchimev/Work/git/appNg/node_modules/nativescript-dev-webpack/projectHelpers.js:38:15)
    at getCompilationContext (/Users/vchimev/Work/git/appNg/node_modules/nativescript-dev-webpack/lib/utils.js:29:20)
    at getContext (/Users/vchimev/Work/git/appNg/node_modules/nativescript-dev-webpack/lib/before-watchPatterns.js:35:12)
    at platforms.map.platform (/Users/vchimev/Work/git/appNg/node_modules/nativescript-dev-webpack/lib/before-watchPatterns.js:22:17)
    at Array.map (<anonymous>)
    at originalMethod.then.originalPatterns (/Users/vchimev/Work/git/appNg/node_modules/nativescript-dev-webpack/lib/before-watchPatterns.js:21:51)
```

**Comment by sis0k0** [comment]
test

**Pull request merged**
