### PR TITLE
fix(JS/TS): use webpack resolver instead of Node.js resolver

### LINKED ISSUE #627: Unable to webpack ts app. Can't resolve 'navigation/example-page'
Using this app https://github.com/NativeScript/nativescript-ui-autocomplete/tree/master/demo and "nativescript-dev-webpack": "~0.15.0" we are unable to build with _tns run ios --bundle --env.uglify --for-device --release_ . Same happens for android. It throws separate error for each xml : 
..
ERROR in ./examples/completion-mode/autocomplete-startswith-page.xml
Module not found: Error: Can't resolve 'navigation/example-page' in '/Users/branzov/Git/nativescript-ui-autocomplete/demo/app/examples/completion-mode'
 @ ./examples/completion-mode/autocomplete-startswith-page.xml 1:69-103 1:189-223
 @ . sync (root|page)\.(xml|css|js|ts|scss)$
 @ ./app.ts

ERROR in ./examples/completion-mode/autocomplete-contains-page.xml
Module not found: Error: Can't resolve 'navigation/example-page' in '/Users/branzov/Git/nativescript-ui-autocomplete/demo/app/examples/completion-mode'
 @ ./examples/completion-mode/autocomplete-contains-page.xml 1:69-103 1:189-223
 @ . sync (root|page)\.(xml|css|js|ts|scss)$
 @ ./app.ts
..

### PR DESCRIPTION
**Pull request by ggodlewski**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA].
- [x] All existing tests are passing: https://github.com/NativeScript/nativescript-dev-webpack/blob/master/CONTRIBUTING.md#testing-locally-by-running-e2e-tests
- [ ] Tests for the changes are included.

## What is the current behavior?

TS files for custom xml components are not budled.

## What is the new behavior?

Fixes #627 

[CLA]: http://www.nativescript.org/cla

### CODE REVIEW

**Comment by radeva** [comment]
Hi @ggodlewski ,

Congratulations on being one of the winners in the {N} First-time contributors contest! 

You can claim your prize by contacting us at nativescriptwinners[at]progress.com not later than Nov 30th 2018 . Make sure you send us the following info: 
👉Your full name 
👉Your email 
👉Your country or residence 

Best regards,
The NativeScript Team

**Comment by ggodlewski** [comment]
Thanks a lot :)

@sis0k0 I think something went wrong with merging into master? Can you check it?
I'd really appreciate if this issue is fixed in the next release.

**Comment by sis0k0** [comment]
test

**Comment by sis0k0** [comment]
test

**Comment by sis0k0** [comment]
Many thanks for the fix, @ggodlewski! It will be released as part of `nativescript-dev-webpack` v0.18.4.

**Pull request merged**
