### PR TITLE
refactor: update Android project path to support next runtime

### PR DESCRIPTION
**Pull request by Plamen5kov**
_problem_
nativescript-dev-webpack is not compatible with new android studio project template

_solution_
need to change bundle output path, depending on the android template version

### CODE REVIEW

**Comment by dtopuzov** [comment]
run ng

**Comment by dtopuzov** [comment]
run ng

**Comment by dtopuzov** [comment]
run ci

**Comment by Plamen5kov** [comment]
run ci

**Comment by Plamen5kov** [comment]
run ng

**Comment by vchimev** [comment]
groceries

**Comment by vchimev** [comment]
Command: `npm run build-android-bundle`

Output:
```
Gradle build...
         + creating include.gradle for plugin /Users/vchimev/Work/tmp/appNG/platforms/node_modules/tns-core-modules-widgets
         + applying plugin configuration from /Users/vchimev/Work/tmp/appNG/platforms/android/app/build/configurations/tns-core-modules-widgets/include.gradle
         + applying user-defined configuration from /Users/vchimev/Work/tmp/appNG/app/App_Resources/Android/app.gradle
         + adding nativescript runtime package dependency: nativescript-optimized
         + adding aar plugin dependency: /Users/vchimev/Work/tmp/appNG/node_modules/tns-core-modules-widgets/platforms/android/widgets-release.aar
false
Running full build

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/vchimev/Work/tmp/appNG/platforms/android/build-tools/android-static-binding-generator/build.gradle' line: 281

* What went wrong:
Execution failed for task ':asbg:generateBindings'.
> No /Users/vchimev/Work/tmp/appNG/platforms/android/build-tools/android-static-binding-generator/bindings.txt was found after runAstParser task was ran! Check to see if there are any .js files inside /Users/vchimev/Work/tmp/appNG/platforms/android/app/src/main/assets/app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
```

**Comment by vchimev** [comment]
Command: `npm run build-android-bundle`

Output:
```
Gradle build...
         + creating include.gradle for plugin /Users/vchimev/Work/tmp/appNG/platforms/node_modules/tns-core-modules-widgets
         + applying plugin configuration from /Users/vchimev/Work/tmp/appNG/platforms/android/app/build/configurations/tns-core-modules-widgets/include.gradle
         + applying user-defined configuration from /Users/vchimev/Work/tmp/appNG/app/App_Resources/Android/app.gradle
         + adding nativescript runtime package dependency: nativescript-optimized
         + adding aar plugin dependency: /Users/vchimev/Work/tmp/appNG/node_modules/tns-core-modules-widgets/platforms/android/widgets-release.aar
false
Running full build

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/vchimev/Work/tmp/appNG/platforms/android/build-tools/android-static-binding-generator/build.gradle' line: 281

* What went wrong:
Execution failed for task ':asbg:generateBindings'.
> No /Users/vchimev/Work/tmp/appNG/platforms/android/build-tools/android-static-binding-generator/bindings.txt was found after runAstParser task was ran! Check to see if there are any .js files inside /Users/vchimev/Work/tmp/appNG/platforms/android/app/src/main/assets/app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
```

**Comment by vchimev** [comment]
ng

**Comment by vchimev** [comment]
groceries

**Comment by vchimev** [comment]
ts

**Comment by vchimev** [comment]
js

**Comment by vchimev** [comment]
sdk

**Comment by vchimev** [comment]
testsappng

**Comment by vchimev** [comment]
sdk

**Comment by vchimev** [comment]
groceries sdk

**Comment by vchimev** [comment]
sdk

**Comment by vchimev** [comment]
*.sdk.*

**Comment by vchimev** [comment]
sdk

**Comment by sis0k0** [comment]
testsappng

**Comment by sis0k0** [comment]
testsappng

**Comment by sis0k0** [comment]
ng

**Comment by vchimev** [comment]
testsappng

**Comment by vchimev** [comment]
testsappng

**Comment by vchimev** [comment]
report > build-android-bundle > verifications > assets

name: vendor.js

isOverSizeLimit: true

error: Asset is over size limit! Expected: 3176000. Actual: 3177377.

**Comment by sis0k0** [comment]
Which is that flavor? Debug/webpack/android/ios/uglify/snapshot? Do you have the project that you measured the 'test' numbers against or a timeline report from it?

**Pull request merged**
