### PR TITLE
refactor: the vendor-plat.ios.ts is used as JavaScript in JavaScript projects, remove typings

### PR DESCRIPTION
**Pull request by PanayotCankov**

### CODE REVIEW

**Comment by vchimev** [comment]
js

**Comment by vchimev** [comment]
javascript-app-android

**Comment by vchimev** [comment]
javascript-app-android

**Comment by vchimev** [comment]
angular-app-android

**Comment by vchimev** [comment]
javascript-app-android

**Comment by PanayotCankov** [comment]
it seems uglifyjs can't handle lambdas...

**Pull request merged**
