### PR TITLE
fix: bundle emitted on save without changes

### PR DESCRIPTION
**Pull request by KristianDD**
## PR Checklist

- [ ] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ ] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [ ] You have signed the [CLA].
- [ ] All existing tests are passing: https://github.com/NativeScript/nativescript-dev-webpack/blob/master/CONTRIBUTING.md#testing-locally-by-running-e2e-tests
- [ ] Tests for the changes are included.

## What is the new behavior?

Fixes/Implements/Closes https://github.com/NativeScript/nativescript-dev-webpack/issues/1096

[CLA]: http://www.nativescript.org/cla

### CODE REVIEW

**Comment by KristianDD** [comment]
test cli-smoke cli-templates

**Comment by rosen-vladimirov** [comment]
Can you please update the commit message to explain in details what's the change and why it is required?

**Comment by rosen-vladimirov** [comment]
test cli-templates cli-run

**Comment by rosen-vladimirov** [comment]
test cli-run

**Comment by miroslavaivanova** [comment]
test cli-run

**Comment by KristianDD** [comment]
test cli-run

**Comment by rosen-vladimirov** [comment]
test cli-run

**Pull request merged**
