### PR TITLE
feat(xml-namespace-loader): add ignore option

### LINKED ISSUE #558: 0.12 messes up fragments
## Issue Checklist

- [x] You are submitting: bug report
- [x] You verified that this is a real problem by searching the [NativeScript Forum] and the other [issues] in this repo.
- [x] You checked our [demo apps] and the [documentation] for sample usage.

## Tell us about the problem
The default register for custom controls is neat, but causes problems with "fragments" that have code behind files. Under fragments I mean files common parts of UI extracted into an XML+TS files. When webpack loader includes those fragments it includes the JS files and not the TS files. So if have not compiled your code it will not load the codebehind. Or even nastier - if you have run normal builds, then run webpack build and make changes to the code it will continue picking up old compiled JS code instead of the new one in the TS file. 

The XML loader should exclude any local modules (i.e. fragments) from the load and leave those to be handled by the `bundle-config` in the app. 

## Local environment

- [x] Platform Mac
- [x] Node version 8 LTS
- [x] NativeScript CLI version 4.1

## Project data

- [x] Platform you are building the app for Both

### PR DESCRIPTION
**Pull request by PeterStaev**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA].
- [ ] All existing tests are passing: https://github.com/NativeScript/nativescript-dev-webpack/blob/master/CONTRIBUTING.md#testing-locally-by-running-e2e-tests
- [ ] Tests for the changes are included.

## What is the current behavior?
There is no way to exclude local modules. This causes problems with typescript based apps. 

## What is the new behavior?
With the `ignore` option user can exclude any local fragments and register them either manually or by using the `registerModules` regex option for the `bundle-config-loader`

Closes #558.

[CLA]: http://www.nativescript.org/cla

### CODE REVIEW

**Comment by PeterStaev** [comment]
If you remove the loader, then you also have to manually register plugins included in the XML files. What I would like is still leave the automatic registration of plugins (which works pretty awesome) and only ignore the local fragments which have issues with the automatic registration.

**Comment by sis0k0** [comment]
test

**Comment by sis0k0** [comment]
test

**Comment by sis0k0** [comment]
test

**Pull request merged**
